### PR TITLE
fixes #1963

### LINKED ISSUE #1963: [Account] Required fields do not take into account conditions
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1

When a required field depends on another field's value, if the required field is not visible (because its condition is not met), then it's still required and the user cannot proceed

Currently, the administrator is forced to make all fields optional, which is blocking the testing of account creation and conditional fields, and is critical for us

### PR DESCRIPTION
**Pull request by Elorfin**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Fixed issues | #1963

Replaces https://github.com/claroline/Claroline/pull/1967

### CODE REVIEW

File: src/main/core/Manager/FacetManager.php [hunk 1]
```diff
@@ -42,4 +43,44 @@ public function deserializeFieldValue($object, $type, $value = null)
...
+                        $displayed = empty($parentValue);
+                        break;
+                    case 'not_empty':
+                        $displayed = !empty($parentValue);
+                        break;
+                }
+
+                return $displayed;
+            }
+        }
```
Comment (maieutiquer) [inline src/main/core/Manager/FacetManager.php:82]: We had to add `return true;` between those two lines:
```

            return true;
```
https://github.com/konsept-ch/Claroline/pull/63/files

I'll retest with and without this line (I don't remember what issue it was solving) and I'll create a new Issue and/or PR
